language: python

python:
  - '3.6'

cache: pip

install:
  - pip install --upgrade pip
  - pip install -r requirements-dev.txt
  - pre-commit install

script:
  - pre-commit run -a
  - pytest --cov=pyitau

after_success:
  - coveralls
